excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jackzhou517.github.io
title: Awesome
email: jiezhou.smr@gmail.com
author: jackzhou517
description: My awesome new site
paginate: 3
google_analytics: 